#!/usr/bin/env ruby

Dir["lib/*.rb"].each {|file| require_relative file }

require "tty-spinner"

if ARGV.first == "-t"
  if ARGV[1] == "zoop"
    puts "testing zoop scraper"
 %w{england scotland wales ireland}.each do |country|
    Pull_Down::Zoopla.new(country).pull_and_check
 end
  else
    puts "testing otm scraper"
    Pull_Down::On_The_Market.new("uk").pull_and_store
  end
else
  %w{england scotland wales ireland}.each do |country|
    spinner = TTY::Spinner.new("[:spinner] Pulling #{country} from zoopla")
    Pull_Down::Zoopla.new(country).pull_and_store do
      spinner.spin
    end
    spinner.success("(Successfull)")
  end
  spinner = TTY::Spinner.new("[:spinner] Pulling uk from On the Market")
  Pull_Down::On_The_Market.new("uk").pull_and_store do
    spinner.spin
  end
  spinner.success("(Successfull)")
end
